#!/usr/bin/env python3
"""Generate src/g2p/ja_data.rs - the kana -> Kokoro phoneme table.

Extracts the `HEPBURN` mapping from misaki's `cutlet.py` (itself adapted from
polm/cutlet, MIT) without importing it, since that module pulls in fugashi,
jaconv and mojimoji. We only want the data.

    python3 tools/gen_ja_data.py     # expects tools/cutlet.py alongside
"""
import os, re, sys, json

HERE = os.path.dirname(os.path.abspath(HERE_FILE := __file__))
OUT = os.path.join(os.path.dirname(HERE), "src", "g2p")

src_path = os.path.join(HERE, "cutlet.py")
if not os.path.exists(src_path):
    sys.exit("missing tools/cutlet.py - see the README's 'Regenerating' section")
src = open(src_path, encoding="utf8").read()

# Everything from the first table to just before the class definitions, minus
# the asserts and the validation loop (which reference names we do not define).
start = src.index("HEPBURN = {")
end = src.index("Katakana_Phonetic_Extensions = [")
block = src[start:end]
keep, skipping = [], False
for line in block.splitlines():
    if line.startswith("assert"):
        continue
    if line.startswith("for k, v in list("):
        skipping = True          # drop the validation loop and its body
        continue
    if skipping:
        if line and not line[0].isspace():
            skipping = False
        else:
            continue
    keep.append(line)
block = "\n".join(keep)

ns = {}
exec(block, ns)
HEPBURN = ns["HEPBURN"]

# The three moraic symbols cutlet resolves contextually rather than by table.
for k in ("っ", "ん", "ー"):
    HEPBURN.pop(k, None)

# cutlet renders these as square brackets, which Kokoro has no token for; the
# model does know parentheses, and that is what cutlet uses for 《》 anyway.
HEPBURN["【"] = "("
HEPBURN["】"] = ")"

KOKORO_PHONEMES = set(json.load(open(os.path.join(HERE, "kokoro_vocab.json")))["vocab"])
bad = {}
for k, v in HEPBURN.items():
    unknown = sorted({c for c in v if c not in KOKORO_PHONEMES})
    if unknown:
        bad[k] = (v, unknown)
if bad:
    for k, (v, u) in list(bad.items())[:20]:
        print(f"  {k!r} -> {v!r} uses {u}", file=sys.stderr)
    sys.exit(f"{len(bad)} entries use phonemes the model has no token for")

def rs(s):
    return "".join(c if 32 <= ord(c) < 127 and c not in '"\\' else f"\\u{{{ord(c):x}}}" for c in s)

rows = sorted(HEPBURN.items())
with open(os.path.join(OUT, "ja_data.rs"), "w", encoding="utf8") as f:
    f.write("// @generated by tools/gen_ja_data.py - do not edit by hand.\n//\n")
    f.write("// Kana (and Japanese punctuation) -> Kokoro phonemes, from the HEPBURN\n")
    f.write("// table in misaki's cutlet.py. Keys are one or two characters; two-character\n")
    f.write("// keys are digraphs (kana + small kana) and are matched first.\n")
    f.write("// The moraic symbols \\u{3063} (sokuon), \\u{3093} (n) and \\u{30fc} (long\n")
    f.write("// vowel) are deliberately absent: they depend on the following mora and are\n")
    f.write("// resolved in ja.rs.\n\n")
    f.write("pub(crate) static KANA: &[(&str, &str)] = &[\n")
    for k, v in rows:
        f.write(f'    ("{rs(k)}", "{rs(v)}"),\n')
    f.write("];\n")

print(f"kana entries: {len(rows)} "
      f"({sum(1 for k, _ in rows if len(k) == 2)} digraphs)")
